# theme       : jekyll-theme-slate
title       : "NDS-Shop"
description : "NDS-Shop - An online database DS Shop for Nintendo 3DS family of systems"
repo        : "TheRinzler65/db-nds-shop"
color       : "#2fbff4"
image       : "https://raw.githubusercontent.com/TheRinzler65/db-nds-shop/main/nds-shop-_logo.png"

sass:
  sass_dir: _sass

collections:
  3ds:
    output: false
  ds:
    output: true
